// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp0cbTDJ2l5LO68jjkAXRfk9ONdPqA66A',
    appId: '1:662510758605:web:6737708aeed58f9560d784',
    messagingSenderId: '662510758605',
    projectId: 'pomodoro-app-c0766',
    authDomain: 'pomodoro-app-c0766.firebaseapp.com',
    storageBucket: 'pomodoro-app-c0766.firebasestorage.app',
    measurementId: 'G-E30JZ2282D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zud7l_vSBBe9tvn3w3iMUZhdza2TmSM',
    appId: '1:662510758605:android:15302f309eaa5ded60d784',
    messagingSenderId: '662510758605',
    projectId: 'pomodoro-app-c0766',
    storageBucket: 'pomodoro-app-c0766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGGlI0QJ35ZbzJQGv2XT51MpoQVsjsQA',
    appId: '1:662510758605:ios:e049b354d056776c60d784',
    messagingSenderId: '662510758605',
    projectId: 'pomodoro-app-c0766',
    storageBucket: 'pomodoro-app-c0766.firebasestorage.app',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGGlI0QJ35ZbzJQGv2XT51MpoQVsjsQA',
    appId: '1:662510758605:ios:e049b354d056776c60d784',
    messagingSenderId: '662510758605',
    projectId: 'pomodoro-app-c0766',
    storageBucket: 'pomodoro-app-c0766.firebasestorage.app',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp0cbTDJ2l5LO68jjkAXRfk9ONdPqA66A',
    appId: '1:662510758605:web:b08d246a05a8e90c60d784',
    messagingSenderId: '662510758605',
    projectId: 'pomodoro-app-c0766',
    authDomain: 'pomodoro-app-c0766.firebaseapp.com',
    storageBucket: 'pomodoro-app-c0766.firebasestorage.app',
    measurementId: 'G-YFYJ571Y6C',
  );
}
